"""
Signal 1: LLM-based classification via Groq.

Asks the model to judge whether a piece of text reads as human-written
or AI-generated, and to return a structured numeric score so it can be
combined with Signal 2 downstream.

llm_score is a float in [0, 1]:
  1.0 = high confidence AI-generated
  0.0 = high confidence human-written
"""
import json
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


PROMPT_TEMPLATE = """You are assisting a content-attribution system. \
Assess whether the following text was likely written by a human or \
generated by an AI language model.

Respond with ONLY a JSON object, no other text, in this exact format:
{{"ai_score": <float between 0 and 1>, "reasoning": "<one short sentence>"}}

ai_score: 1.0 means you are highly confident the text is AI-generated.
0.0 means you are highly confident the text is human-written.
0.5 means you genuinely cannot tell.

Text to assess:
---
{text}
---
"""


def get_llm_score(text: str) -> dict:
    """
    Calls Groq to assess the text. Returns a dict:
        {"llm_score": float, "reasoning": str}
    Falls back to a neutral score if the API call or parsing fails,
    so a single bad response doesn't crash the pipeline.
    """
    client = _get_client()
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "user", "content": PROMPT_TEMPLATE.format(text=text)}
            ],
            temperature=0,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()
        parsed = json.loads(raw)
        score = float(parsed.get("ai_score", 0.5))
        score = max(0.0, min(1.0, score))  # clamp defensively
        return {
            "llm_score": score,
            "reasoning": parsed.get("reasoning", ""),
        }
    except Exception as e:
        # Fail safe: neutral score + visible reasoning that something went wrong.
        return {"llm_score": 0.5, "reasoning": f"signal_error: {e}"}


if __name__ == "__main__":
    # Quick manual test — run `python signals_llm.py` directly.
    samples = [
        "Artificial intelligence represents a transformative paradigm shift "
        "in modern society. It is important to note that while the benefits "
        "of AI are numerous, it is equally essential to consider the ethical "
        "implications.",
        "ok so i finally tried that new ramen place downtown and honestly? "
        "underwhelming. the broth was fine but they put WAY too much sodium "
        "in it and i was thirsty for like three hours after.",
    ]
    for s in samples:
        print(get_llm_score(s))
